version: "3.5"
services:
  kanban-frontend:
    build:
      context: .
      args:
        - SCHEMA_ENDPOINT=http://localhost:3000/api/graphql
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - TAILWIND_MODE=watch
