version: "3.5"
services:
  kanban-frontend:
    build:
      context: .
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - SCHEMA_ENDPOINT=${SCHEMA_ENDPOINT}
    networks:
      - kanban-frontend-network

networks:
  kanban-frontend-network:
    name: kanban-network
